### ISSUE TITLE
Webpack plugin not working

### ISSUE THREAD

**Issue by sacru2red** [ryoppippi/unplugin-typia#137]
https://github.com/sacru2red/ryoppippi__unplugin-typia__fail
I am trying version@0.4.12

throw errors "typia is not setup"

**Comment by ryoppippi** [comment]
- you need to use the right TypeScript Version ( I mean <5.5.0 for now)
- you need to use default import like `import typia from 'typia'`. idk why.
- https://github.com/ryoppippi/unplugin-typia/issues/136 is solves.

Overall, this issue is Typia's issue, not this plugin.	


So, in my environment, I did the following steps and works fine.

```
git clone https://github.com/sacru2red/ryoppippi__unplugin-typia__fail
npm i
npx jsr add @ryoppippi/unplugin-typia@latest -D
npm i typescript@5.4.5
```

Then, fix `import` statement.
And it works!!

**Comment by ryoppippi** [comment]
Again, thank you for reporting this.
I added the webpack examples
https://github.com/ryoppippi/unplugin-typia/commit/0332014

**Comment by ryoppippi** [comment]
@sacru2red Have you ever tried the new version?

**Comment by sacru2red** [comment]
@ryoppippi 

- `use default import` dont help me
- It's working with typescript@5.4.5 (5.4.4 not works)
Thanks

**Comment by sacru2red** [comment]
https://github.com/sacru2red/ryoppippi__unplugin-typia__fail/actions/runs/9688317394/job/26734629478
windows works, but not linux OS

**Comment by ryoppippi** [comment]
@sacru2red 
Thanks, but this is odd!!
Hmm, maybe because of typia or ts-patch issue?
